version: '3'

services:
  updated_base: &updated_base
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - /livdesk/PRD-updated/storage:/app/storage

  updated_rails:
    <<: *updated_base
    depends_on:
      - updated_postgres
      - updated_redis
    ports:
      - '127.0.0.1:3300:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  updated_sidekiq:
    <<: *updated_base
    depends_on:
      - updated_postgres
      - updated_redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  updated_postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '127.0.0.1:55432:5432'
    volumes:
      - /livdesk/PRD-updated/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  updated_redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - /livdesk/PRD-updated/redis:/data
    ports:
      - '127.0.0.1:16379:6379'
