name: (deprecated) Build and Push Chatwoot Dev Images to GHCR

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image (chatwoot-development)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-development:latest
          build-args: |
            RAILS_ENV=development
            NODE_ENV=development
            BUNDLE_WITHOUT=
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push rails image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/rails.Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-rails:latest
          build-args: |
            RAILS_ENV=development
            NODE_ENV=development
            BUNDLE_WITHOUT=
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push vite image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/vite.Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-vite:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
