name: Build and Push Chatwoot Production Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image (chatwoot-production)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-production:latest
          build-args: |
            RAILS_ENV=production
            NODE_ENV=production
            BUNDLE_WITHOUT=development:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push rails image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/rails.Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-rails-prod:latest
          build-args: |
            RAILS_ENV=production
            NODE_ENV=production
            BUNDLE_WITHOUT=development:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push vite image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/vite.Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-vite-prod:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
