name: Build and Push Chatwoot Dev Images to GHCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile.base
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-dev-base:latest

      - name: Build and push dev rails image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-rails:dev
          build-args: |
            RAILS_ENV=development
            NODE_ENV=development
            BUNDLE_WITHOUT=

      - name: Build and push dev vite image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfiles/vite.Dockerfile
          push: true
          tags: ghcr.io/gridtechrnd/chatwoot-vite:dev
          build-args: |
            NODE_ENV=development