name: Publish Codespace Base Image

on:
  workflow_dispatch:

jobs:
  publish-code-space-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Codespace Base Image
        run: |
          docker compose -f .devcontainer/docker-compose.base.yml build base
          docker push ghcr.io/gridtechrnd/chatwoot_codespace:latest