name: Test GHCR Push Permission

on:
  workflow_dispatch:

jobs:
  test-ghcr-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and tag hello-world
        run: |
          docker pull hello-world
          docker tag hello-world ghcr.io/gridtechrnd/hello-world:test

      - name: Push to GHCR
        run: |
          docker push ghcr.io/gridtechrnd/hello-world:test